# Generated by Django 5.0.7 on 2024-07-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='stuff',
        ),
        migrations.AddField(
            model_name='react',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='product',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
