# Generated by Django 5.0.7 on 2024-07-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_stuff_react_price_react_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='price',
        ),
    ]
