# Generated by Django 5.0.7 on 2024-07-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_react_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='product',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='department',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
