# Generated by Django 5.0.7 on 2024-07-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_product_react_employee_react_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
    ]
